[package]
name = "aws"
version = "0.0.1"
edition = "2021"
publish = false
license = "Apache-2.0"

[features]
failpoints = ["fail/failpoints"]

[dependencies]
async-trait = "0.1"

aws-config = "1.2.1"
aws-credential-types = { version = "1.2.0", features = ["hardcoded-credentials"] }
aws-sdk-kms = "1.22.0"
aws-sdk-s3 = "1.16.0"
aws-smithy-runtime = "1.4.0"
aws-smithy-runtime-api = "1.5.0"
aws-smithy-types =  { version = "1.1.8", features = ["byte-stream-poll-next"] }

base64 = "0.13.0"
bytes = "1.0"
cloud = { workspace = true }
fail = "0.5"
futures = "0.3"
futures-util = { version = "0.3", default-features = false, features = ["io"] }
# This is only a dependency to vendor openssl for rusoto. It's not clear exactly
# how openssl is built for tikv, but it seems to be controlled by grpcio. This
# makes `cargo test -p aws` link correctly.
grpcio = { workspace = true }
http = "0.2.0"
hyper = "0.14"
hyper-tls = "0.5"
kvproto = { workspace = true }
lazy_static = "1.3"
md5 = "0.7.0"
prometheus = { version = "0.13", default-features = false, features = ["nightly"] }
slog = { workspace = true }
slog-global = { workspace = true }
thiserror = "1.0"
tikv_util = { workspace = true }
# better to not use slog-global, but pass in the logger
tokio = { version = "1.5", features = ["time"] }
tokio-util = { version = "0.7" }
url = "2.0"
uuid = { version = "0.8", features = ["v4"] }

[dev-dependencies]
aws-smithy-runtime = { version = "1.4.0", features = ["test-util", "client"] }
base64 = "0.13"
futures = "0.3"
