[package]
name = "br-stream"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [features]
# default = ["protobuf-codec"]
# protobuf-codec = ["kvproto/protobuf-codec"]
# prost-codec = ["prost", "kvproto/protobuf"]

[dependencies]

tokio = { version = "1.5", features = ["rt-multi-thread", "macros", "time", "sync"] }
async-trait = { version = "0.1" }
thiserror = "1"
bytes = "0.4"
etcd-client = "0.7"
kvproto = { git = "https://github.com/pingcap/kvproto.git", branch = "br-stream"}
tokio-stream = "0.1"
protobuf = { version = "2.8", features = ["bytes"] }
regex = "1"